### ISSUE TITLE
Setup E-mail service

### ISSUE THREAD

**Issue by Naapperas** [semanadeinformatica/website#10]
We should setup an email service in order to make the most out of Laravel's native password reset features.

**Comment by Naapperas** [comment]
@ttoino wasn't this already dealt with when we changed to Laravel Sail?

**Comment by ttoino** [comment]
> @ttoino wasn't this already dealt with when we changed to Laravel Sail?

I don't think so, I believe we still need to configure it, but we have mailpit setup for local testing.
