### ISSUE TITLE
Create the database SQL file

### ISSUE THREAD

**Issue by toni-santos** [semanadeinformatica/website#12]
Related to #2, we now have a UML representation of the database, as such we should start creating the SQL file for the database.
Below is the UML.

![SINF website-ConceptualModel, v2 drawio](https://github.com/semanadeinformatica/website-2023/assets/72560332/95381cd6-a047-4b2a-aad7-433feae306fe)

Top priority should be the Auth, Activity and SINF sections.

**Comment by Naapperas** [comment]
On this. Laravel has migrations, so if we manage to develop the Database schema through that we should. However, i believe things like foreign keys and restrictions are hard or impossible to do: in that case we should resort to a single schema file.

**Comment by ttoino** [comment]
After reading the migration documentation, [foreign keys are possible](https://laravel.com/docs/9.x/migrations#foreign-key-constraints), but constraints are limited to nullable/nonnull.

**Comment by Naapperas** [comment]
> After reading the migration documentation, [foreign keys are possible](https://laravel.com/docs/9.x/migrations#foreign-key-constraints), but constraints are limited to nullable/nonnull.

Is there a way for us to inject raw SQL in the migration code? If there is we could easily place the conditions for restrictions. I haven't looked much into the documentation tho.

**Comment by Naapperas** [comment]
> > After reading the migration documentation, [foreign keys are possible](https://laravel.com/docs/9.x/migrations#foreign-key-constraints), but constraints are limited to nullable/nonnull.
> 
> Is there a way for us to inject raw SQL in the migration code? If there is we could easily place the conditions for restrictions. I haven't looked much into the documentation tho.

Also, can one create triggers using Laravel? I believe we cannot

**Comment by ttoino** [comment]
We can use the DB façade to run raw SQL

**Comment by CiscoPr** [comment]
![SINF website-ConceptualModel, v2 drawio](https://github.com/semanadeinformatica/website-2023/assets/79597450/970588bf-88ac-4ae2-a836-94ab25af42e2)
just updated the Socials and added github
