### ISSUE TITLE
Add booleans to models

### ISSUE THREAD

**Issue by Naapperas** [semanadeinformatica/website#197]
We should add a boolean to Enrollments that indicates if the user has gone to the receiving area to get their goodies.
We should add a boolean to the relation between products and an enrollment to indicate that the product has been redeemed.

**Comment by Naapperas** [comment]
This could be done using QR codes (CC @ttoino)

**Comment by pedronunes19** [comment]
The "relation between products and an enrollment" doesn't exist yet, so that can be done with the rest of the backend.
Check in can be a quest.

**Comment by pedronunes19** [comment]
Maybe it can't who knows

**Comment by ttoino** [comment]
Closing this as the enrollment use case is covered by quests and the product use case was done in #278.
