### ISSUE TITLE
Allow new event types

### ISSUE THREAD

**Issue by pedronunes19** [semanadeinformatica/website#208]
Panel, cocktail session, company visits, etc.

**Comment by Naapperas** [comment]
This is already allowed through the EventType model.

**Comment by pedronunes19** [comment]
I didn't word very well

**Comment by pedronunes19** [comment]
![image](https://github.com/semanadeinformatica/website-2023/assets/75331417/74dc8a2f-920d-4f07-bf97-285a3377e843)
